As4242421022 dal1 - change from IPv6 LL to ULA
routedbits/dn42-peers pull request #220
Opened 2024-11-22 21:46 UTC by bsdrocker

2024-11-22 21:52 UTC, jvoss requested changes

2024-11-22 21:52 UTC, jvoss commented on routers/router.dal1.yml
> +  extended_nexthop: true
```suggestion
  ipv4: <FIXME: add an IPv4 address for this tunnel>
  ipv6: fd2e:5e5e:83ad::1022:207
  multiprotocol: true
```

Let's try this without enabling `extended_nexthop` given the difficulties in #216.

2024-11-23 02:34 UTC, jvoss approved these changes

2024-11-23 14:28 UTC, merged

2024-11-23 15:21 UTC, jvoss commented
@bsdrocker this has been deployed.

With this configuration, remember that you will need a static route to our end of the wireguard tunnel:

```
ip -6 route fdb1:e72a:343d::5/128 via <your wireguard interface>
```

And then configure BGP peering to `fdb1:e72a:343d::5`. Note that you may need to enable multihop or disable connected checks depending on your situation.

Otherwise if you want to use a subnet on the tunnel such that each end is part of the same network we will need an address for our side and the subnet size.

2024-11-23 21:18 UTC, bsdrocker commented
@jvoss I can't ping you and I also see BGP trying to establish from your side from the link-local address still. BGP on my side is stuck in Connect.

2024-11-23 21:46 UTC, jvoss commented
Did you add the static route I mentioned?

Also the old peering is still configured and will be reconciled tonight after automation runs again.

2024-11-23 22:31 UTC, bsdrocker commented
Indeed I have:

```
bsdrocker@dal-us-01:~$ ip -6 route |grep wg1
fd2e:5e5e:8a3d::1022:207 dev wg1 proto kernel metric 256 pref medium
fdb1:e72a:343d::5 dev wg1 proto kernel metric 256 pref medium
bsdrocker@dal-us-01:~$
```

```
bsdrocker@dal-us-01:~$ ping fdb1:e72a:343d::5 -I wg1
PING fdb1:e72a:343d::5 (fdb1:e72a:343d::5) from fd2e:5e5e:8a3d::1022:207 wg1: 56 data bytes
^C
--- fdb1:e72a:343d::5 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4109ms

bsdrocker@dal-us-01:~$
```

2024-11-23 22:32 UTC, bsdrocker commented
I realized what the issue is - there's actually a typo in the PR. I'll have to fix it.