Add AS4242422002 peerings
routedbits/dn42-peers pull request #242
Opened 2024-12-25 23:29 UTC by hello-smile6

This PR should connect my personal dn42 network's nodes to your network. My end is ready to go and will be deployed shortly.

2024-12-25 23:31 UTC, jvoss requested changes
Let's leave a blank line between peers to improve human readability.

2024-12-25 23:31 UTC, jvoss commented on routers/router.chi1.yml
> +- name: KIX-9PFS
```suggestion

- name: KIX-9PFS
```

2024-12-25 23:31 UTC, jvoss commented on routers/router.chi1.yml
> +- name: KIX-9PFS
```suggestion

- name: KIX-9PFS
```

2024-12-25 23:31 UTC, jvoss commented on routers/router.dal1.yml
> +- name: US1-9PFS
```suggestion

- name: US1-9PFS
```

2024-12-25 23:31 UTC, jvoss commented on routers/router.fnc1.yml
> +- name: US3-9PFS
```suggestion

- name: US3-9PFS
```

2024-12-25 23:31 UTC, jvoss commented on routers/router.iad1.yml
> +- name: US2-9PFS
```suggestion

- name: US2-9PFS
```

2024-12-25 23:31 UTC, jvoss commented on routers/router.lon1.yml
> +- name: UK1-9PFS
```suggestion

- name: UK1-9PFS
```

2024-12-26 01:06 UTC, jvoss commented on routers/router.chi1.yml
> +
```suggestion
```

Removing an extra line.

2024-12-26 01:11 UTC, jvoss requested changes
Please add your public endpoint information. We do not currently support totally dynamic peers.

2024-12-26 01:11 UTC, jvoss commented on routers/router.chi1.yml
> +  wireguard:
Missing remote_address and remote_port.

2024-12-26 01:11 UTC, jvoss commented on routers/router.dal1.yml
> +  wireguard:
Missing remote_address and remote_port.

2024-12-26 01:11 UTC, jvoss commented on routers/router.fnc1.yml
> +  wireguard:
Missing remote_address and remote_port.

2024-12-26 01:11 UTC, jvoss commented on routers/router.iad1.yml
> +  wireguard:
Missing remote_address and remote_port.

2024-12-26 01:11 UTC, jvoss commented on routers/router.lon1.yml
> +  wireguard:
Missing remote_address and remote_port.

2024-12-26 01:12 UTC, hello-smile6 commented
Does every peering need a public endpoint?

2024-12-26 01:58 UTC, jvoss approved these changes

2024-12-26 01:59 UTC, merged